---

- name: Remove existing Vim packages
  become: yes
  ignore_errors: yes
  yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - vim-X11
    - vim-common
    - vim-enhanced
    - vim-filesystem
    - vim-fugitive
    - vim-go
    - vim-gtk-syntax
    - vim-halibut
    - vim-jellybeans
    - vim-toml
    - vim-vimoutliner

- name: Install required packages
  package:
    name: sudo
    update_cache: yes
    state: present

- name: Ensure dependency packags installed
  become: yes
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - gcc
    - gcc-c++
    - ruby
    - ruby-devel
    - perl-devel
    - perl-ExtUtils-Embed
    - python-devel
    - ncurses
    - ncurses-devel
    - lua
    - lua-devel
    - git

- name: Git clone Vim source code
  git:
    repo: 'https://github.com/vim/vim.git'
    dest: vim_source

- name: Compile Vim source code
  shell: |
    ./configure --prefix=/usr/local    \
    --enable-multibyte     \
    --enable-pythoninterp  \
    --enable-rubyinterp    \
    --with-ruby-command=/usr/bin/ruby \
    --with-features=huge   \
    --enable-luainterp     \
    --with-lua-prefix=/usr

    make
  args:
    chdir: vim_source

- name: Install compiled Vim binary
  become: yes
  shell: make install
  args:
    chdir: vim_source
