---
packages:
  - chrony            # ntp required

ansible_dep_packages:
  - gcc
  - gcc-c++
  - python-virtualenv
  - python-pip
  - python-devel
  - libffi-devel
  - openssl-devel
  - libyaml-devel
  - sshpass
  - git

ntp_service_name: chronyd
