---

- name: Deploy source code
  copy: src="{{ resources_dir }}/bin/{{ target }}.tar.gz" dest="{{ deploy_dir }}" mode=0644

- name: Remove existing packages
  ignore_errors: yes
  yum:
    name: "{{ default_target }}"
    state: absent

- name: Ensure dependency packages installed
  yum:
    name: "{{ target_dependency }}"

- name: Unarchive source code
  command: "tar -zxf {{ deploy_dir }}/{{ target }}.tar.gz"
  args:
    warn: no

- name: Compile source code
  command: "{{ compile_command }}"
  args:
    chdir: "{{ target }}"

- name: Install compiled binary
  shell: make install
  args:
    chdir: "{{ target }}"

- name: Clean up temp files
  file: 
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ target }}"
    - "{{ target }}.tar.gz"
