---

- name: Deploy {{ target }} source code
  copy: src="{{ resources_dir }}/bin/{{ target }}.tar.gz" dest="{{ deploy_dir }}" mode=0644
  register: source_code

- name: Remove existing packages
  ignore_errors: yes
  yum:
    name: "{{ default_target }}"
    state: absent
  when: source_code is changed

- name: Ensure dependency packages installed
  yum:
    name: "{{ target_dependency }}"
  when: source_code is changed

- name: Unpacking {{ target }} source code
  command: "tar -zxf {{ deploy_dir }}/{{ target }}.tar.gz"
  args:
    warn: no
  when: source_code is changed
  register: source_code_unpack

- name: Compile {{ target }} source code
  shell: >
    {{ compile_command }}
  args:
    chdir: "{{ target }}"
  when: source_code_unpack is changed
  register: source_code_compiled

- name: Install {{ target }} compiled binary
  shell: >
    {{ install_command }}
  args:
    chdir: "{{ target }}"
  when: source_code_compiled is changed
  register: source_code_installed

- name: Clean up temp files
  file: 
    path: "{{ tmp_path }}"
    state: absent
  loop_control:
    loop_var: tmp_path
  with_items:
    - "{{ target }}"
    - "{{ target }}.tar.gz"
  when: source_code_installed is changed
