---
- name: Setup default Git configuration
  git_config:
    name="{{ item.name }}"
    scope=global
    value="{{ item.value }}"
  with_items:
    - { name: "user.name", value: "dantin" }
    - { name: "user.email", value: "chengjie.ding@gmail.com" }
    - { name: "core.editor", value: "vim" }
