---

- name: Load variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - default.yml
      paths:
        -- vars

- name: Download vim source code
  get_url:
    url: "{{ vim_github_url }}/archive/v{{ default_vim_version }}.tar.gz"
    dest: "{{ deploy_dir }}/source/vim.tar.gz"
    checksum: "sha256:100192a0845f7d0f4206ccf6f446559367b9a6bb10560c9cf8b7768353142d8e"
    use_proxy: no
    validate_certs: no

- name: Build customized vim from source
  include_role:
    name: build-binary
  vars:
    this_role_name: vim
    source_file: vim.tar.gz
    compile_dir: "vim-{{ default_vim_version }}"
    compile_command: >
      ./configure --prefix=/usr/local
      --with-features=huge
      --enable-cscope=yes
      --enable-multibyte=yes
      --enable-perlinterp=yes
      --enable-pythoninterp=yes
      --with-python-command=/usr/bin/python
      --with-python-config-dir=/lib64/python2.7/config
      --enable-python3interp=yes
      --with-python3-command=/usr/bin/python3
      --with-python-config-dir=/lib64/python3.6/config-3.6m-x86_64-linux-gnu
      --enable-rubyinterp=yes
      --with-ruby-command=/usr/bin/ruby
      --enable-luainterp=yes
      --with-lua-prefix=/usr
      --with-compiledby="David Ding" &&
      make
    install_command:
      make install
    dependency_packages:
      - gcc
      - gcc-c++
      - ncurses
      - ncurses-devel
      - ruby
      - ruby-devel
      - lua
      - lua-devel
      - luajit
      - luajit-devel
      - ctags
      - python
      - python-devel
      - python3
      - python3-devel
      - tcl-devel
      - perl
      - perl-devel
      - perl-ExtUtils-ParseXS
      - perl-ExtUtils-XSpp
      - perl-ExtUtils-CBuilder
      - perl-ExtUtils-Embed

- name: Set vim as default editor
  shell: >
    update-alternatives --install /usr/bin/editor editor /usr/local/bin/vim 1 &&
    update-alternatives --set editor /usr/local/bin/vim
  become: yes
