---

- name: Create user directories
  file: path={{ item }} state=directory mode=0755
  with_items:
    - "/home/{{ ansible_user }}/{{ documents_dir }}"
    - "/home/{{ ansible_user }}/{{ code_dir }}"
    - "/home/{{ ansible_user }}/{{ temp_dir }}"
