---

- name: Set default Git configuration
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  with_items:
    - { name: "user.name", value: "dantin" }
    - { name: "user.email", value: "chengjie.ding@gmail.com" }
    - { name: "core.editor", value: "vim" }
    - { name: "push.default", value: "simple" }
