---

- name: Download vim-config code
  git:
    repo: "https://github.com/dantin/vim-config.git"
    dest: "/home/{{ ansible_user }}/{{ code_dir }}/vim-config"

- name: Configure Vim
  shell: >
    sh -c ./bootstrap.sh
  args:
    chdir: "/home/{{ ansible_user }}/{{ code_dir }}/vim-config"
