---

- name: Update vim-config from github.com
  git:
    repo: "https://github.com/dantin/vim-config.git"
    dest: "/home/{{ ansible_user }}/{{ code_dir }}/vim-config"

- name: Configure Vim using vim-config
  shell: >
    sh -c ./bootstrap.sh
  args:
    chdir: "/home/{{ ansible_user }}/{{ code_dir }}/vim-config"
