---

- name: Determine if .oh-my-zsh exists
  stat:
    path: ~/.oh-my-zsh
  register: oh_my_zsh_st

- name: Download oh-my-zsh install script
  get_url:
    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: "{{ deploy_dir }}/scripts/install_zsh.sh"
    checksum: "sha256:8e772598a453e6ebeeb2774e0a9022e2e9d61f98c47f5aed4005744e86a2771f"
    use_proxy: no
    validate_certs: no
    mode: 0755
  when: oh_my_zsh_st.stat.exists == False

- name: Install oh-my-zsh
  raw: echo no | sh -c "{{ deploy_dir }}/scripts/install_zsh.sh"
  when: oh_my_zsh_st.stat.exists == False

- name: Change default shell
  raw: chsh -s /usr/bin/zsh {{ ansible_user }}
  become: yes
