---

- name: Install zsh binary
  become: yes
  package:
    name: zsh
    state: present

- name: Upload the install.sh script
  template:
    src: install.sh.j2
    dest: "{{ ansible_user_dir }}/install.sh"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: Install oh-my-zsh
  raw: "sh -c {{ ansible_user_dir }}/install.sh"
