---

- name: Install zsh from repository
  package:
    name: zsh
    update_cache: yes
    state: present
  become: yes

- name: Update zsh to /etc/shells
  blockinfile:
    path: /etc/shells
    block: |
        /usr/bin/zsh
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
  become: yes
