---
- name: Load variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution_major_version }}.yml"
        - defaults.yml
      paths:
        -- ../base/vars

- block:
    - name: Install epel-release
      package:
        name: epel-release
        update_cache: yes
        state: present

    - name: Upgrade all packages
      yum:
        name: "{{ os_repository }}"
        state: present
  when: (ansible_os_family|lower == "redhat" and ansible_distribution_major_version|int == 7)

- name: Install base packages
  package:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items: "{{ base_package | join(',') }}"

- name: Make sure the NTP service is started
  service:
    name: "{{ ntp_service_name }}"
    state: started

- name: Make sure the NTP service is enabled
  service:
    name: "{{ ntp_service_name }}"
    enabled: yes
  ignore_errors: true
