---

- name: Fail if username is empty
  fail:
    msg: "The username is empty. This usually means there is no 'username' defined or 'username' is empty."
  when: username is not defined or username == ""

- name: Add account for {{ username }}
  user: name={{ username }} shell=/bin/bash createhome=yes

- name: Set {{ username }} authorized key
  authorized_key:
    user: "{{ username }}"
    key: "{{ item }}"
    state: present
  with_file:
    - pubkey.pub

- name: Update sudoers file
  lineinfile:
    dest: /etc/sudoers
    insertafter: EOF
    line: '{{ username }} ALL=(ALL) NOPASSWD: ALL'
    regexp: '^{{ username }} .*'
    state: present
