---

- name: Load variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution_major_version }}.yml"
        - defaults.yml
      paths:
        -- ../tools/vars

- name: Build Git from source
  include_tasks: "git.yml"

- name: Build Vim from source
  include_tasks: "vim.yml"
