---

- include_vars: file={{ playbook_dir }}/conf/binary_packages.yml

- name: Set Tmux distribution fact
  set_fact:
    tmux_distribution: "{{ item.name }}-{{ item.version }}"
  when: (item.name|lower == "tmux")
  with_items: "{{ third_party_code }}"

- name: Deploy Tmux source code
  copy: src="{{ resources_dir }}/bin/{{ tmux_distribution }}.tar.gz" dest="{{ deploy_dir }}" mode=0644

- name: Remove existing Tmux packages
  ignore_errors: yes
  yum:
    name: "{{ default_tmux_packages }}"
    state: absent

- name: Ensure dependency packages installed
  yum:
    name: "{{ tmux_dep_packages }}"

- name: Unarchive source code
  shell: |
    tar -zxf {{ deploy_dir }}/{{ tmux_distribution }}.tar.gz
  args:
    warn: no

- name: Compile source code
  shell: |
    ./configure

    make 
  args:
    chdir: "{{ tmux_distribution }}"

- name: Install compiled binary
  shell: make install
  args:
    chdir: "{{ tmux_distribution }}"

- name: Clean up temp files
  file: 
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ tmux_distribution }}"
    - "{{ tmux_distribution }}.tar.gz"
