---

- include_vars: file={{ playbook_dir }}/conf/binary_packages.yml

- name: Set Vim distribution fact
  set_fact:
    vim_distribution: "{{ item.name }}-{{ item.version }}"
  when: (item.name|lower == "vim")
  with_items: "{{ third_party_packages }}"

- name: Deploy Vim source code
  copy: src="{{ resources_dir }}/bin/{{ vim_distribution }}.tar.gz" dest="{{ deploy_dir }}" mode=0644

- name: Remove existing Vim packages
  ignore_errors: yes
  yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - vim-X11
    - vim-common
    - vim-enhanced
    - vim-filesystem
    - vim-fugitive
    - vim-go
    - vim-gtk-syntax
    - vim-halibut
    - vim-jellybeans
    - vim-toml
    - vim-vimoutliner

- name: Install sudo package
  package:
    name: sudo
    update_cache: yes
    state: present

- name: Ensure dependency packages installed
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - gcc
    - gcc-c++
    - ruby
    - ruby-devel
    - perl-devel
    - perl-ExtUtils-Embed
    - python-devel
    - ncurses
    - ncurses-devel
    - lua
    - lua-devel
    - git

- name: Unarchive Vim source code
  shell: |
    tar -zxf {{ deploy_dir }}/{{ vim_distribution }}.tar.gz
  args:
    warn: no

- name: Compile Vim source code
  shell: |
    ./configure --prefix=/usr/local   \
    --enable-multibyte                \
    --enable-pythoninterp             \
    --enable-rubyinterp               \
    --with-ruby-command=/usr/bin/ruby \
    --with-features=huge              \
    --enable-luainterp                \
    --with-lua-prefix=/usr

    make
  args:
    chdir: "{{ vim_distribution }}"

- name: Install compiled Vim binary
  shell: make install
  args:
    chdir: "{{ vim_distribution }}"
