---

- include_vars: file={{ playbook_dir }}/conf/binary_packages.yml

- name: Set Vim distribution fact
  set_fact:
    vim_distribution: "{{ item.name }}-{{ item.version }}"
  when: (item.name|lower == "vim")
  with_items: "{{ third_party_code }}"

- name: Deploy Vim source code
  copy: src="{{ resources_dir }}/bin/{{ vim_distribution }}.tar.gz" dest="{{ deploy_dir }}" mode=0644

- name: Remove existing Vim packages
  ignore_errors: yes
  yum:
    name: "{{ default_vim_packages }}"
    state: absent

- name: Install sudo package
  package:
    name: sudo
    update_cache: yes
    state: present

- name: Ensure dependency packages installed
  yum:
    name: "{{ vim_dep_packages }}"

- name: Unarchive source code
  shell: |
    tar -zxf {{ deploy_dir }}/{{ vim_distribution }}.tar.gz
  args:
    warn: no

- name: Compile source code
  shell: |
    ./configure --prefix=/usr/local   \
    --enable-multibyte                \
    --enable-pythoninterp             \
    --enable-rubyinterp               \
    --with-ruby-command=/usr/bin/ruby \
    --with-features=huge              \
    --enable-luainterp                \
    --with-lua-prefix=/usr

    make
  args:
    chdir: "{{ vim_distribution }}"

- name: Install compiled binary
  shell: make install
  args:
    chdir: "{{ vim_distribution }}"

- name: Clean up temp files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ vim_distribution }}"
    - "{{ vim_distribution }}.tar.gz"
