---

- name: Preflight checks
  hosts: localhost
  gather_facts: false
  roles:
    - preflight-checks

- name: Configure nodes
  hosts: develop
  any_errors_fatal: true
  roles:
    - node-config
  tags: node-config
