---

- name: Initializing deployment target
  hosts: all
  gather_facts: false
  tags: always
  roles:
    - check-config-dynamic

- name: Prepare docker-compose
  hosts: all
  tags: docker-compose
  roles:
    - docker-compose
