---

- name: Initializing deployment target
  hosts: all
  gather_facts: false
  tags: always
  roles:
    - check-config-dynamic

- name: Prepare tmux
  hosts: all
  gather_facts: false
  tags: tmux
  roles:
    - tmux

- name: Prepare docker-compose
  hosts: all
  gather_facts: false
  tags: docker-compose
  roles:
    - docker-compose

- name: Prepare git
  hosts: all
  gather_facts: false
  tags: git
  roles:
    - git

- name: Prepare cmake
  hosts: all
  gather_facts: false
  tags: cmake
  roles:
    - cmake
