---

- name: Preflight checks
  hosts: localhost
  gather_facts: false
  roles:
    - preflight-checks

- name: Initializing deployment target
  hosts: all
  gather_facts: false
  tags: always
  roles:
    - check-config-dynamic

- name: Prepare tmux
  hosts: all
  gather_facts: false
  tags: tmux
  roles:
    - tmux

- name: Prepare docker-engine
  hosts: all
  gather_facts: false
  tags: docker-engine
  roles:
    - docker-engine

- name: Prepare docker-compose
  hosts: all
  gather_facts: false
  tags: docker-compose
  roles:
    - docker-compose

- name: Prepare git
  hosts: all
  gather_facts: false
  tags: git
  roles:
    - git

- name: Prepare cmake
  hosts: all
  gather_facts: false
  tags: cmake
  roles:
    - cmake

- name: Prepare python3
  hosts: all
  gather_facts: false
  tags: python3
  roles:
    - python3

- name: Prepare vim
  hosts: all
  gather_facts: false
  tags: vim
  roles:
    - vim

- name: Prepare zsh
  hosts: all
  gather_facts: false
  tags: zsh
  roles:
    - zsh

- name: Prepare pyenv
  hosts: all
  gather_facts: false
  tags: pyenv
  roles:
    - pyenv
