---

- name: Preflight checks
  hosts: localhost
  gather_facts: false
  roles:
    - preflight-checks

- name: Install Common Software on Nodes
  hosts: develop
  any_errors_fatal: true
  become: yes
  roles:
    - common
  tags: common

- name: Setup development environment
  hosts: develop
  any_errors_fatal: true
  become: yes
  roles:
    - devtools
  tags: devtools
