---
- name: Create the required Ansible groups
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Add nodes to the develop-box group and groups representing the host_groups
      include_tasks: "clouds/add_nodes_{{ cloud_name }}.yml"
      with_items: "{{ nodes|default(omit) }}"

    - name: Initialize the develop_box list
      set_fact:
        develop_box: []

    - block:
        - name: Populate the develop_box list (dynamic blueprint)
          set_fact:
            develop_groups: "{{ develop_groups }} + [ '{{ item.host_group }}' ]"
          when: groups[item.host_group] is defined and groups[item.host_group]|length > 0
          with_items: "{{ blueprint_dynamic }}"
